---
version: "3.8"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/Chicago
      - UMASK_SET=022
      - VERSION=docker
    volumes:
      - /media_server/configs/plex:/config
      - /media_server/plex:/data/plex
    restart: unless-stopped
    
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=2001
      - PGID=2000
      - TZ=America/Chicago
    volumes:
      - /media_server/configs/sabnzbd:/config
      - /media_server/sabnzbd/complete:/media_server/complete
      - /media_server/sabnzbd/incomplete:/media_server/incomplete
      - /media_server/plex:/media_server/plex
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped
  
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=2002
      - PGID=2000
      - TZ=America/Chicago
    volumes:
      - /media_server/configs/sonarr:/config
      - /media_server:/media_server
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=2003
      - PGID=2000
      - TZ=America/Chicago
    volumes:
      - /media_server/configs/radarr:/config
      - /media_server:/media_server
    ports:
      - 7878:7878
    restart: unless-stopped
  
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=2004
      - PGID=2000
      - TZ=America/Chicago
    volumes:
      - /media_server/configs/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    
  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    ports:
    - '9090:8080'
